version: "3.8"
services:
    service-1:
        container_name: trigger
        build:
            context: ./service-1
            dockerfile: ../Dockerfile
        image: trigger:latest
        ports:
            - "8080:8080"
        restart: unless-stopped
        environment:
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
        networks:
            - jaeger-example
    service-2:
        container_name: animal
        build:
            context: ./service-2
            dockerfile: ../Dockerfile
        image: animal:latest
        expose:
            - "9000"
        restart: unless-stopped
        environment:
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
        networks:
            - jaeger-example
    service-3:
        container_name: scientist
        build:
            context: ./service-3
            dockerfile: ../Dockerfile
        image: scientist:latest
        expose:
            - "8090"
        restart: unless-stopped
        environment:
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
        networks:
            - jaeger-example
    jaeger:
        container_name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"
        environment:
            - COLLECTOR_ZIPKIN_HOST_PORT=:9411
        networks:
            - jaeger-example

networks:
    jaeger-example:
        driver: bridge

