receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317
      http:
        include_metadata: true
        cors:
          allowed_origins:
            - http://localhost:3000
            - http://localhost:8080
            - http://localhost
          allowed_headers:
            - Example-Header
          max_age: 7200

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]